package com.dianpoint.summer.test.component;

import com.dianpoint.summer.beans.BeansException;
import com.dianpoint.summer.beans.factory.support.DefaultListableBeanFactory;
import com.dianpoint.summer.core.scanner.ClassPathComponentScanner;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassPathComponentScannerTest {

    @Test
    public void testScanFindsComponentClasses() {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        ClassPathComponentScanner scanner = new ClassPathComponentScanner(factory);
        int count = scanner.scan("com.dianpoint.summer.test.component");
        assertThat(count).isGreaterThanOrEqualTo(3);
    }

    @Test
    public void testAutoGeneratedBeanName() throws BeansException {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        ClassPathComponentScanner scanner = new ClassPathComponentScanner(factory);
        scanner.scan("com.dianpoint.summer.test.component");

        HelloComponent bean = (HelloComponent) factory.getBean("helloComponent");
        assertThat(bean).isNotNull();
        assertThat(bean.sayHello()).isEqualTo("Hello");
    }

    @Test
    public void testCustomBeanName() throws BeansException {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        ClassPathComponentScanner scanner = new ClassPathComponentScanner(factory);
        scanner.scan("com.dianpoint.summer.test.component");

        CustomNameComponent bean = (CustomNameComponent) factory.getBean("customName");
        assertThat(bean).isNotNull();
    }

    @Test
    public void testNonAnnotatedClassNotScanned() {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        ClassPathComponentScanner scanner = new ClassPathComponentScanner(factory);
        scanner.scan("com.dianpoint.summer.test.component");

        assertThat(factory.containsSingleton("nonAnnotatedClass")).isFalse();
        assertThat(factory.containsBeanDefinition("nonAnnotatedClass")).isFalse();
    }

    @Test
    public void testMultipleComponentClassesRegistered() throws BeansException {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        ClassPathComponentScanner scanner = new ClassPathComponentScanner(factory);
        int count = scanner.scan("com.dianpoint.summer.test.component");
        assertThat(count).isGreaterThanOrEqualTo(3);

        HelloComponent hello = (HelloComponent) factory.getBean("helloComponent");
        ServiceComponent service = (ServiceComponent) factory.getBean("serviceComponent");
        CustomNameComponent custom = (CustomNameComponent) factory.getBean("customName");
        assertThat(hello).isNotNull();
        assertThat(service).isNotNull();
        assertThat(custom).isNotNull();
    }

    @Test
    public void testEmptyPackageReturnsZero() {
        DefaultListableBeanFactory factory = new DefaultListableBeanFactory();
        ClassPathComponentScanner scanner = new ClassPathComponentScanner(factory);
        int count = scanner.scan("com.dianpoint.summer.nonexistent");
        assertThat(count).isEqualTo(0);
    }
}
